import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import Data from "../models/dataModel.js";
import Population from "../models/populationModel.js";
import Infrastructure from "../models/infrastructureModel.js";
import Environment from "../models/environmentModel.js";
import Transport from "../models/transportModel.js";

// PDF Buffer validation helper
const validatePDFBuffer = (buffer) => {
    if (!buffer || buffer.length === 0) {
        throw new Error('Generated PDF buffer is empty');
    }
    if (!Buffer.isBuffer(buffer)) {
        throw new Error('Generated data is not a valid buffer');
    }
    return buffer;
};

// ✅ Generate comprehensive dashboard report
export const generateReport = async (req, res) => {
    try {
        const userId = req.user.id;
        const username = req.user.username;
        const { city = "Pune", year = new Date().getFullYear() } = req.query;

        console.log(`📊 Generating comprehensive dashboard report for ${username} (${city}, ${year})`);

        // Fetch all data for the dashboard report
        let [populationData, infrastructureData, environmentData, transportData, userActions] = await Promise.all([
            Population.find({ city }).sort({ year: -1 }).lean(),
            Infrastructure.find({ city }).sort({ year: -1 }).lean(),
            Environment.find({ userId, city }).sort({ createdAt: -1 }).lean(),
            Transport.find({ city }).sort({ date: -1 }).lean(),
            Data.find({ userId }).sort({ createdAt: -1 }).lean()
        ]);

        if (environmentData.length === 0) {
            environmentData = await Environment.find({ city }).sort({ createdAt: -1 }).lean();
        }

        console.log(`✅ Data fetched: Pop=${populationData.length}, Infra=${infrastructureData.length}, Env=${environmentData.length}, Trans=${transportData.length}`);

        // Calculate dashboard statistics
        const populationStats = calculatePopulationStats(populationData);
        const infrastructureStats = calculateInfrastructureStats(infrastructureData);
        const environmentStats = calculateEnvironmentStats(environmentData);
        const transportStats = calculateTransportStats(transportData);

        // Create PDF
        const doc = new jsPDF();

        // Cover Page
        doc.setFontSize(24);
        doc.setTextColor(40, 53, 147);
        doc.text("URBAN GROWTH DASHBOARD REPORT", 105, 40, { align: 'center' });

        doc.setFontSize(16);
        doc.setTextColor(100, 100, 100);
        doc.text(`${city} Urban Analytics | ${year}`, 105, 60, { align: 'center' });

        doc.setFontSize(12);
        doc.text(`Generated by: ${username}`, 105, 75, { align: 'center' });
        doc.text(new Date().toLocaleDateString(), 105, 85, { align: 'center' });

        doc.setDrawColor(40, 53, 147);
        doc.setLineWidth(2);
        doc.line(20, 95, 190, 95);

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("AI-Powered Urban Growth Dashboard - Comprehensive Analysis", 105, 100, { align: 'center' });

        // Page 2: Executive Summary
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(40, 53, 147);
        doc.text("Executive Summary - Dashboard Overview", 20, 20);

        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);

        const summaryText = `
This comprehensive dashboard report provides insights into urban growth patterns for ${city}. 
The data represents real-time analytics from the AI Urban Growth Dashboard.

KEY PERFORMANCE INDICATORS (KPIs):
${populationStats ? `• Total Population: ${(populationStats.latestPopulation / 1000000).toFixed(2)} Million` : '• Population data not available'}
${populationStats ? `• Annual Growth Rate: ${populationStats.avgGrowthRate.toFixed(2)}%` : ''}
${infrastructureStats ? `• Smart City Score: ${infrastructureStats.avgSmartScore.toFixed(1)}/100` : '• Infrastructure data not available'}
${environmentStats ? `• Average AQI: ${environmentStats.avgAQI.toFixed(1)}` : '• Environment data not available'}
${transportStats ? `• Traffic Congestion: ${transportStats.avgCongestion.toFixed(1)}%` : '• Transport data not available'}

DASHBOARD HIGHLIGHTS:
1. POPULATION: ${populationStats ? populationStats.growthTrend : 'No data available'}
2. INFRASTRUCTURE: ${infrastructureStats ? infrastructureStats.trend : 'No data available'}
3. ENVIRONMENT: ${environmentStats ? getPollutionText(environmentStats.pollutionLevel) : 'No data available'}
4. TRANSPORT: ${transportStats ? transportStats.efficiency : 'No data available'}

DATA SOURCES:
• Population: ${populationData.length} records
• Infrastructure: ${infrastructureData.length} records  
• Environment: ${environmentData.length} records
• Transport: ${transportData.length} records
• User Activity: ${userActions.length} actions

${generateDashboardRecommendations(populationStats, infrastructureStats, environmentStats, transportStats)}
    `.trim();

        doc.text(summaryText, 20, 35, { maxWidth: 170 });

        // Add module pages
        if (populationData.length > 0) addPopulationPage(doc, populationData, populationStats);
        if (infrastructureData.length > 0) addInfrastructurePage(doc, infrastructureData, infrastructureStats);
        if (environmentData.length > 0) addEnvironmentPage(doc, environmentData, environmentStats);
        if (transportData.length > 0) addTransportPage(doc, transportData, transportStats);

        // Footer on all pages
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
            doc.text(`Report ID: ${city.toUpperCase()}-${Date.now().toString().slice(-8)}`, 105, 290, { align: 'center' });
        }

        // Convert to buffer and send
        const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
        validatePDFBuffer(pdfBuffer);

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=${city}_comprehensive_report_${Date.now()}.pdf`);
        res.setHeader('Content-Length', pdfBuffer.length);
        res.setHeader('Access-Control-Expose-Headers', 'Content-Disposition');

        res.send(pdfBuffer);

        console.log(`✅ Report generated successfully: ${pdfBuffer.length} bytes`);

        // Log async
        Data.create({
            userId, username,
            action: "DASHBOARD_REPORT_GENERATED",
            analysisResult: `Comprehensive dashboard report generated for ${city}`,
            city,
        }).catch(err => console.error("Error logging report:", err));

    } catch (error) {
        console.error("❌ Report Generation Error:", error);
        res.status(500).json({
            success: false,
            message: "Error generating dashboard report",
            error: error.message,
            stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
        });
    }
};

export const generateModuleDashboardReport = async (req, res) => {
    const { module } = req.params;
    try {
        const userId = req.user.id;
        const username = req.user.username;
        const city = req.query.city || "Pune";

        console.log(`📊 Generating ${module} dashboard report for ${username}`);

        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.setTextColor(40, 53, 147);
        doc.text(`${module.charAt(0).toUpperCase() + module.slice(1)} Dashboard Report`, 105, 20, { align: 'center' });

        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`${city} Urban Analytics | ${new Date().toLocaleDateString()}`, 105, 30, { align: 'center' });
        doc.text(`Generated by: ${username}`, 105, 40, { align: 'center' });

        // Add module-specific content
        switch (module.toLowerCase()) {
            case 'population':
                const popData = await Population.find({ city }).sort({ year: -1 }).lean();
                const popStats = calculatePopulationStats(popData);
                addPopulationDashboard(doc, popData, popStats);
                break;
            case 'infrastructure':
                const infraData = await Infrastructure.find({ city }).sort({ year: -1 }).lean();
                const infraStats = calculateInfrastructureStats(infraData);
                addInfrastructureDashboard(doc, infraData, infraStats);
                break;
            case 'environment':
                let envData = await Environment.find({ userId, city }).sort({ createdAt: -1 }).lean();
                if (envData.length === 0) {
                    envData = await Environment.find({ city }).sort({ createdAt: -1 }).lean();
                }
                const envStats = calculateEnvironmentStats(envData);
                addEnvironmentDashboard(doc, envData, envStats);
                break;
            case 'transport':
                const transData = await Transport.find({ city }).sort({ date: -1 }).lean();
                const transStats = calculateTransportStats(transData);
                addTransportDashboard(doc, transData, transStats);
                break;
            default:
                throw new Error(`Unknown module: ${module}`);
        }

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`${module.toUpperCase()} Report - Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
        }

        const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
        validatePDFBuffer(pdfBuffer);

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=${module}_report_${city}_${Date.now()}.pdf`);
        res.setHeader('Content-Length', pdfBuffer.length);
        res.setHeader('Access-Control-Expose-Headers', 'Content-Disposition');

        res.send(pdfBuffer);

        console.log(`✅ ${module} report generated: ${pdfBuffer.length} bytes`);

        Data.create({
            userId, username,
            action: "MODULE_DASHBOARD_REPORT",
            analysisResult: `${module} dashboard report generated`,
            city,
        }).catch(err => console.error("Error logging:", err));

    } catch (error) {
        console.error(`❌ ${module} Report Error:`, error);
        res.status(500).json({
            success: false,
            message: `Error generating ${module} dashboard report`,
            error: error.message
        });
    }
};

// Helper functions to add pages
function addPopulationPage(doc, data, stats) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setTextColor(40, 53, 147);
    doc.text("1. Population Dashboard Analytics", 20, 20);

    if (stats) {
        autoTable(doc, {
            startY: 30,
            head: [['Dashboard Metric', 'Value', 'Status']],
            body: [
                ['Total Population', (stats.latestPopulation / 1000000).toFixed(2) + 'M', 'Current'],
                ['Annual Growth Rate', stats.avgGrowthRate.toFixed(2) + '%', getTrendIcon(stats.avgGrowthRate)],
                ['Population Density', stats.avgDensity.toLocaleString() + '/km²', 'Urban Density'],
                ['Growth Trend', stats.growthTrend, '']
            ],
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] }
        });
    }
}

function addInfrastructurePage(doc, data, stats) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setTextColor(40, 53, 147);
    doc.text("2. Infrastructure Dashboard Analytics", 20, 20);

    if (stats && data[0]) {
        autoTable(doc, {
            startY: 30,
            head: [['Infrastructure Component', 'Current Value', 'Score/Status']],
            body: [
                ['Smart City Index', data[0].smartCityScore + '/100', data[0].smartCityScore > 75 ? 'Excellent' : 'Good'],
                ['Road Network', data[0].roadsKm + ' km', stats.roadsScore.toFixed(1) + '/100'],
                ['Healthcare Facilities', data[0].hospitals + ' hospitals', stats.healthScore.toFixed(1) + '/100'],
                ['Education Institutions', data[0].schools + ' schools', stats.educationScore.toFixed(1) + '/100']
            ],
            theme: 'striped',
            headStyles: { fillColor: [139, 92, 246] }
        });
    }
}

function addEnvironmentPage(doc, data, stats) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setTextColor(40, 53, 147);
    doc.text("3. Environment Dashboard Analytics", 20, 20);

    if (stats) {
        autoTable(doc, {
            startY: 30,
            head: [['Environmental Parameter', 'Average Value', 'Status']],
            body: [
                ['Air Quality Index (AQI)', stats.avgAQI.toFixed(1), getAQIStatus(stats.avgAQI)],
                ['PM2.5 Levels', stats.avgPM25.toFixed(1) + ' µg/m³', getPM25Status(stats.avgPM25)],
                ['Green Cover', stats.avgGreenCover.toFixed(1) + '%', getGreenCoverStatus(stats.avgGreenCover)],
                ['Pollution Level', stats.pollutionLevel, '']
            ],
            theme: 'striped',
            headStyles: { fillColor: [34, 197, 94] }
        });
    }
}

function addTransportPage(doc, data, stats) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setTextColor(40, 53, 147);
    doc.text("4. Transport Dashboard Analytics", 20, 20);

    if (stats) {
        autoTable(doc, {
            startY: 30,
            head: [['Transport Metric', 'Average Value', 'Condition']],
            body: [
                ['Traffic Congestion', stats.avgCongestion.toFixed(1) + '%', getCongestionStatus(stats.avgCongestion)],
                ['Average Speed', stats.avgSpeed.toFixed(1) + ' km/h', stats.efficiency],
                ['Traffic Index', stats.avgTrafficIndex.toFixed(1), '']
            ],
            theme: 'striped',
            headStyles: { fillColor: [249, 115, 22] }
        });
    }
}

// Module dashboard functions
function addPopulationDashboard(doc, data, stats) {
    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Population Dashboard Overview", 20, 55);

    if (stats && data.length > 0) {
        autoTable(doc, {
            startY: 65,
            head: [['Dashboard Metric', 'Value', 'Status']],
            body: [
                ['Total Population', (stats.latestPopulation / 1000000).toFixed(3) + ' Million', 'Current'],
                ['Annual Growth Rate', stats.avgGrowthRate.toFixed(2) + '%', getTrendIcon(stats.avgGrowthRate)],
                ['Population Density', stats.avgDensity.toLocaleString() + ' per km²', 'Urban Density']
            ],
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] }
        });

        const tableData = data.slice(0, 10).map(pop => [
            pop.year.toString(),
            (pop.totalPopulation / 1000000).toFixed(3) + 'M',
            pop.growthRate + '%',
            pop.density.toLocaleString()
        ]);

        autoTable(doc, {
            startY: doc.lastAutoTable.finalY + 15,
            head: [['Year', 'Population', 'Growth', 'Density']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] }
        });
    }
}

function addInfrastructureDashboard(doc, data, stats) {
    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Infrastructure Dashboard Overview", 20, 55);

    if (stats && data.length > 0) {
        autoTable(doc, {
            startY: 65,
            head: [['Infrastructure Component', 'Current Value', 'Score/Status']],
            body: [
                ['Smart City Index', data[0].smartCityScore + '/100', data[0].smartCityScore > 75 ? 'Excellent' : 'Good'],
                ['Road Network', data[0].roadsKm + ' km', stats.roadsScore.toFixed(1) + '/100'],
                ['Healthcare Facilities', data[0].hospitals.toString() + ' hospitals', stats.healthScore.toFixed(1) + '/100']
            ],
            theme: 'striped',
            headStyles: { fillColor: [139, 92, 246] }
        });
    }
}

function addEnvironmentDashboard(doc, data, stats) {
    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Environment Dashboard Overview", 20, 55);

    if (stats && data.length > 0) {
        autoTable(doc, {
            startY: 65,
            head: [['Parameter', 'Average Value', 'Status']],
            body: [
                ['Air Quality Index', stats.avgAQI.toFixed(1), getAQIStatus(stats.avgAQI)],
                ['PM2.5 Levels', stats.avgPM25.toFixed(1) + ' µg/m³', getPM25Status(stats.avgPM25)],
                ['Green Cover', stats.avgGreenCover.toFixed(1) + '%', getGreenCoverStatus(stats.avgGreenCover)]
            ],
            theme: 'striped',
            headStyles: { fillColor: [34, 197, 94] }
        });
    }
}

function addTransportDashboard(doc, data, stats) {
    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Transport Dashboard Overview", 20, 55);

    if (stats && data.length > 0) {
        autoTable(doc, {
            startY: 65,
            head: [['Transport Metric', 'Average Value', 'Condition']],
            body: [
                ['Traffic Congestion', stats.avgCongestion.toFixed(1) + '%', getCongestionStatus(stats.avgCongestion)],
                ['Average Speed', stats.avgSpeed.toFixed(1) + ' km/h', stats.efficiency]
            ],
            theme: 'striped',
            headStyles: { fillColor: [249, 115, 22] }
        });
    }
}

// Calculation functions
function calculatePopulationStats(populationData) {
    if (!populationData || populationData.length === 0) return null;

    const latest = populationData[0];
    const earliest = populationData[populationData.length - 1];

    const totalGrowth = latest.totalPopulation - earliest.totalPopulation;
    const growthPercentage = (totalGrowth / earliest.totalPopulation * 100).toFixed(2);
    const avgGrowthRate = populationData.reduce((sum, item) => sum + item.growthRate, 0) / populationData.length;
    const avgDensity = populationData.reduce((sum, item) => sum + item.density, 0) / populationData.length;

    return {
        latestPopulation: latest.totalPopulation,
        avgGrowthRate,
        avgDensity,
        growthTrend: avgGrowthRate > 2.5 ? 'Rapid Growth ↗' : avgGrowthRate > 1.5 ? 'Moderate Growth →' : 'Stable ↘',
        yearRange: { start: earliest.year, end: latest.year },
        totalGrowth,
        growthPercentage
    };
}

function calculateInfrastructureStats(infrastructureData) {
    if (!infrastructureData || infrastructureData.length === 0) return null;

    const latest = infrastructureData[0];
    const avgSmartScore = infrastructureData.reduce((sum, item) => sum + item.smartCityScore, 0) / infrastructureData.length;

    const roadsScore = Math.min(100, (latest.roadsKm / 1000) * 100);
    const healthScore = Math.min(100, (latest.hospitals / 100) * 100);
    const educationScore = Math.min(100, (latest.schools / 500) * 100);
    const housingScore = latest.housingIndex || 65;

    const overallScore = (roadsScore * 0.2 + healthScore * 0.2 + educationScore * 0.2 + housingScore * 0.2 + latest.smartCityScore * 0.2);

    return {
        roadsScore, healthScore, educationScore, housingScore,
        smartCityScore: latest.smartCityScore,
        avgSmartScore,
        overallScore,
        trend: latest.smartCityScore > 75 ? 'Improving ↗' : latest.smartCityScore > 60 ? 'Stable →' : 'Needs Attention ↘'
    };
}

function calculateEnvironmentStats(environmentData) {
    if (!environmentData || environmentData.length === 0) return null;

    const latest = environmentData[0];
    const avgAQI = environmentData.reduce((sum, item) => sum + (item.aqi || 0), 0) / environmentData.length;
    const avgPM25 = environmentData.reduce((sum, item) => sum + (item.pm25 || 0), 0) / environmentData.length;
    const avgGreenCover = environmentData.reduce((sum, item) => sum + (item.greenCover || 0), 0) / environmentData.length;

    return {
        avgAQI, avgPM25, avgGreenCover,
        pollutionLevel: latest.pollutionLevel || 'Moderate',
        lastUpdated: latest.createdAt,
        dataPoints: environmentData.length
    };
}

function calculateTransportStats(transportData) {
    if (!transportData || transportData.length === 0) return null;

    const avgCongestion = transportData.reduce((sum, item) => sum + (item.congestionLevel || 0), 0) / transportData.length;
    const avgSpeed = transportData.reduce((sum, item) => sum + (item.avgSpeed || 0), 0) / transportData.length;
    const avgTrafficIndex = transportData.reduce((sum, item) => sum + (item.trafficIndex || 0), 0) / transportData.length;

    return {
        avgCongestion, avgSpeed, avgTrafficIndex,
        peakHours: '8-10 AM, 5-7 PM',
        weeklyPattern: 'Heavier on weekdays',
        efficiency: avgSpeed > 40 ? 'Good Flow ✅' : avgSpeed > 25 ? 'Moderate ⚠️' : 'Poor 🚫'
    };
}

// Utility functions
function getTrendIcon(growthRate) {
    if (growthRate > 2.5) return '↗ Rapid Growth';
    if (growthRate > 1.5) return '→ Moderate Growth';
    return '↘ Stable';
}

function getAQIStatus(aqi) {
    if (!aqi) return 'N/A';
    if (aqi <= 50) return 'Good ✅';
    if (aqi <= 100) return 'Moderate ⚠️';
    if (aqi <= 150) return 'Unhealthy ❗';
    return 'Hazardous ☠️';
}

function getPM25Status(pm25) {
    if (!pm25) return 'N/A';
    if (pm25 <= 12) return 'Good';
    if (pm25 <= 35) return 'Moderate';
    return 'Unhealthy';
}

function getGreenCoverStatus(cover) {
    if (!cover) return 'N/A';
    if (cover > 30) return 'Excellent';
    if (cover > 20) return 'Good';
    return 'Moderate';
}

function getCongestionStatus(congestion) {
    if (!congestion) return 'N/A';
    if (congestion <= 30) return 'Light ✅';
    if (congestion <= 50) return 'Moderate ⚠️';
    return 'Heavy ❗';
}

function getPollutionText(level) {
    switch (level) {
        case 'Good': return 'Good air quality';
        case 'Moderate': return 'Moderate pollution levels';
        case 'Unhealthy': return 'Elevated pollution';
        default: return 'Moderate conditions';
    }
}

function generateDashboardRecommendations(popStats, infraStats, envStats, transStats) {
    const recommendations = [];

    if (popStats && popStats.avgGrowthRate > 2.5) {
        recommendations.push('• Accelerate infrastructure development');
    }
    if (infraStats && infraStats.overallScore < 70) {
        recommendations.push('• Increase smart city investment');
    }
    if (envStats && envStats.avgAQI > 100) {
        recommendations.push('• Implement pollution control measures');
    }
    if (transStats && transStats.avgCongestion > 60) {
        recommendations.push('• Enhance public transportation');
    }

    if (recommendations.length === 0) {
        recommendations.push('• Continue current strategies');
    }

    return '\nRECOMMENDATIONS:\n' + recommendations.join('\n');
}

// ✅ Get report summary
export const getReportSummary = async (req, res) => {
    try {
        const userId = req.user.id;
        const city = req.query.city || "Pune";

        const summary = {
            population: await Population.countDocuments({ city }),
            infrastructure: await Infrastructure.countDocuments({ city }),
            environment: await Environment.countDocuments({ userId, city }),
            transport: await Transport.countDocuments({ city }),
            userActions: await Data.countDocuments({ userId }),
            lastGenerated: await Data.findOne({ userId, action: "DASHBOARD_REPORT_GENERATED" }).sort({ createdAt: -1 })
        };

        res.json({
            success: true,
            message: "Report summary fetched successfully",
            summary
        });
    } catch (error) {
        console.error("❌ Report Summary Error:", error);
        res.status(500).json({
            success: false,
            message: "Error fetching report summary",
            error: error.message
        });
    }
};