import { jsPDF } from "jspdf";
import "jspdf-autotable";
import Data from "../models/dataModel.js";
import Population from "../models/populationModel.js";
import Infrastructure from "../models/infrastructureModel.js";
import Environment from "../models/environmentModel.js";
import Transport from "../models/transportModel.js";

// PDF Buffer validation helper
const validatePDFBuffer = (buffer) => {
    if (!buffer || buffer.length === 0) {
        throw new Error('Generated PDF buffer is empty');
    }
    if (!Buffer.isBuffer(buffer)) {
        throw new Error('Generated data is not a valid buffer');
    }
    return buffer;
};

// ✅ Generate comprehensive dashboard report
export const generateReport = async (req, res) => {
    try {
        const userId = req.user.id;
        const username = req.user.username;
        const { reportType = "comprehensive", city = "Pune", year = new Date().getFullYear() } = req.query;

        console.log(`📊 Generating ${reportType} dashboard report for ${username} (${city}, ${year})`);

        // Fetch all data for the dashboard report
        const [
            populationData,
            infrastructureData,
            environmentData,
            transportData,
            userActions
        ] = await Promise.all([
            Population.find({ city }).sort({ year: -1 }),
            Infrastructure.find({ city }).sort({ year: -1 }),
            Environment.find({ userId, city }).sort({ createdAt: -1 }),
            Transport.find({ city }).sort({ date: -1 }),
            Data.find({ userId }).sort({ createdAt: -1 })
        ]);

        // Calculate dashboard statistics
        const populationStats = calculatePopulationStats(populationData);
        const infrastructureStats = calculateInfrastructureStats(infrastructureData);
        const environmentStats = calculateEnvironmentStats(environmentData);
        const transportStats = calculateTransportStats(transportData);

        // Create PDF
        const doc = new jsPDF();

        // Cover Page
        doc.setFontSize(24);
        doc.setTextColor(40, 53, 147);
        doc.text("URBAN GROWTH DASHBOARD REPORT", 105, 40, { align: 'center' });

        doc.setFontSize(16);
        doc.setTextColor(100, 100, 100);
        doc.text(`${city} Urban Analytics | ${year}`, 105, 60, { align: 'center' });

        doc.setFontSize(12);
        doc.text(`Generated by: ${username}`, 105, 75, { align: 'center' });
        doc.text(new Date().toLocaleDateString(), 105, 85, { align: 'center' });

        // Add decorative elements
        doc.setDrawColor(40, 53, 147);
        doc.setLineWidth(2);
        doc.line(20, 95, 190, 95);

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("AI-Powered Urban Growth Dashboard - Comprehensive Analysis", 105, 100, { align: 'center' });

        // Page 2: Executive Summary (Dashboard Overview)
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(40, 53, 147);
        doc.text("Executive Summary - Dashboard Overview", 20, 20);

        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);

        const summaryText = `
This comprehensive dashboard report provides insights into urban growth patterns for ${city}. 
The data represents real-time analytics from the AI Urban Growth Dashboard.

KEY PERFORMANCE INDICATORS (KPIs):
${populationStats ? `• Total Population: ${(populationStats.latestPopulation / 1000000).toFixed(2)} Million` : ''}
${populationStats ? `• Annual Growth Rate: ${populationStats.avgGrowthRate.toFixed(2)}%` : ''}
${infrastructureStats ? `• Smart City Score: ${infrastructureStats.avgSmartScore.toFixed(1)}/100` : ''}
${environmentStats ? `• Average AQI: ${environmentStats.avgAQI.toFixed(1)}` : ''}
${transportStats ? `• Traffic Congestion: ${transportStats.avgCongestion.toFixed(1)}%` : ''}

DASHBOARD HIGHLIGHTS:
1. POPULATION: ${populationStats ? populationStats.growthTrend : 'Stable growth pattern'}
2. INFRASTRUCTURE: ${infrastructureStats ? infrastructureStats.trend : 'Steady development'}
3. ENVIRONMENT: ${environmentStats ? getPollutionText(environmentStats.pollutionLevel) : 'Moderate conditions'}
4. TRANSPORT: ${transportStats ? transportStats.efficiency : 'Standard traffic patterns'}

DATA SOURCES:
• Population: ${populationData.length} records
• Infrastructure: ${infrastructureData.length} records  
• Environment: ${environmentData.length} records
• Transport: ${transportData.length} records
• User Activity: ${userActions.length} actions

${generateDashboardRecommendations(populationStats, infrastructureStats, environmentStats, transportStats)}
    `.trim();

        doc.text(summaryText, 20, 35, { maxWidth: 170 });

        // Page 3: Population Dashboard
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(40, 53, 147);
        doc.text("1. Population Dashboard Analytics", 20, 20);

        if (populationStats && populationData.length > 0) {
            // Population Summary Table (Dashboard KPIs)
            doc.autoTable({
                startY: 30,
                head: [['Dashboard Metric', 'Value', 'Status']],
                body: [
                    ['Total Population', (populationStats.latestPopulation / 1000000).toFixed(2) + 'M', 'Current'],
                    ['Annual Growth Rate', populationStats.avgGrowthRate.toFixed(2) + '%', getTrendIcon(populationStats.avgGrowthRate)],
                    ['Population Density', populationStats.avgDensity.toLocaleString() + '/km²', 'Urban Density'],
                    ['Data Coverage', `${populationStats.yearRange.start}-${populationStats.yearRange.end}`, `${populationStats.growthPercentage}% total growth`],
                    ['Growth Trend', populationStats.growthTrend, '']
                ],
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246] }
            });

            // Population Data Table (Recent Years)
            const chartY = doc.lastAutoTable.finalY + 15;
            doc.setFontSize(14);
            doc.setTextColor(40, 53, 147);
            doc.text("Recent Population Data", 20, chartY);

            const recentData = populationData.slice(0, 5).map(pop => [
                pop.year,
                (pop.totalPopulation / 1000000).toFixed(3) + 'M',
                pop.growthRate + '%',
                pop.density.toLocaleString() + '/km²'
            ]);

            doc.autoTable({
                startY: chartY + 10,
                head: [['Year', 'Population', 'Growth Rate', 'Density']],
                body: recentData,
                theme: 'grid',
                headStyles: { fillColor: [59, 130, 246] }
            });
        } else {
            doc.setFontSize(12);
            doc.setTextColor(100, 100, 100);
            doc.text("No population dashboard data available", 20, 35);
        }

        // Page 4: Infrastructure Dashboard
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(40, 53, 147);
        doc.text("2. Infrastructure Dashboard Analytics", 20, 20);

        if (infrastructureStats && infrastructureData.length > 0) {
            // Infrastructure Scorecard (Dashboard View)
            doc.autoTable({
                startY: 30,
                head: [['Infrastructure Component', 'Current Value', 'Score/Status']],
                body: [
                    ['Smart City Index', infrastructureData[0].smartCityScore + '/100', infrastructureData[0].smartCityScore > 75 ? 'Excellent' : 'Good'],
                    ['Road Network', infrastructureData[0].roadsKm + ' km', infrastructureStats.roadsScore.toFixed(1) + '/100'],
                    ['Healthcare Facilities', infrastructureData[0].hospitals + ' hospitals', infrastructureStats.healthScore.toFixed(1) + '/100'],
                    ['Education Institutions', infrastructureData[0].schools + ' schools', infrastructureStats.educationScore.toFixed(1) + '/100'],
                    ['Housing Index', infrastructureData[0].housingIndex + '/100', infrastructureData[0].housingIndex > 70 ? 'Good' : 'Needs Improvement'],
                    ['Overall Score', infrastructureStats.overallScore.toFixed(1) + '/100', infrastructureStats.trend]
                ],
                theme: 'striped',
                headStyles: { fillColor: [139, 92, 246] }
            });

            // Infrastructure Development Trend
            const trendY = doc.lastAutoTable.finalY + 15;
            doc.setFontSize(14);
            doc.setTextColor(40, 53, 147);
            doc.text("Infrastructure Development Trend", 20, trendY);

            if (infrastructureData.length >= 3) {
                const trendData = infrastructureData.slice(0, 5).map(infra => [
                    infra.year,
                    infra.roadsKm + ' km',
                    infra.hospitals,
                    infra.schools,
                    infra.smartCityScore + '/100'
                ]);

                doc.autoTable({
                    startY: trendY + 10,
                    head: [['Year', 'Roads', 'Hospitals', 'Schools', 'Smart Score']],
                    body: trendData,
                    theme: 'grid',
                    headStyles: { fillColor: [139, 92, 246] }
                });
            }
        }

        // Page 5: Environment Dashboard
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(40, 53, 147);
        doc.text("3. Environment Dashboard Analytics", 20, 20);

        if (environmentStats && environmentData.length > 0) {
            // Environment Quality Dashboard
            doc.autoTable({
                startY: 30,
                head: [['Environmental Parameter', 'Average Value', 'Status']],
                body: [
                    ['Air Quality Index (AQI)', environmentStats.avgAQI.toFixed(1), getAQIStatus(environmentStats.avgAQI)],
                    ['PM2.5 Levels', environmentStats.avgPM25.toFixed(1) + ' µg/m³', getPM25Status(environmentStats.avgPM25)],
                    ['Green Cover', environmentStats.avgGreenCover.toFixed(1) + '%', getGreenCoverStatus(environmentStats.avgGreenCover)],
                    ['Pollution Level', environmentStats.pollutionLevel, ''],
                    ['Data Points', environmentData.length + ' readings', 'Based on recent measurements']
                ],
                theme: 'striped',
                headStyles: { fillColor: [34, 197, 94] },
                didDrawCell: (data) => {
                    if (data.section === 'body' && data.column.index === 2) {
                        const status = data.cell.raw;
                        if (status.includes('✅') || status.includes('Good') || status === 'Excellent') {
                            data.cell.styles.textColor = [34, 197, 94];
                        } else if (status.includes('⚠️') || status === 'Moderate') {
                            data.cell.styles.textColor = [234, 179, 8];
                        } else if (status.includes('❗') || status.includes('Poor')) {
                            data.cell.styles.textColor = [239, 68, 68];
                        }
                    }
                }
            });

            // Recent Environment Readings
            const recentEnvY = doc.lastAutoTable.finalY + 15;
            doc.setFontSize(14);
            doc.setTextColor(40, 53, 147);
            doc.text("Recent Environmental Readings", 20, recentEnvY);

            if (environmentData.length > 0) {
                const recentData = environmentData.slice(0, 5).map(env => [
                    new Date(env.createdAt).toLocaleDateString(),
                    env.aqi || 'N/A',
                    env.pm25 || 'N/A',
                    env.greenCover || 'N/A',
                    env.pollutionLevel || 'N/A'
                ]);

                doc.autoTable({
                    startY: recentEnvY + 10,
                    head: [['Date', 'AQI', 'PM2.5', 'Green Cover%', 'Pollution Level']],
                    body: recentData,
                    theme: 'grid',
                    headStyles: { fillColor: [34, 197, 94] }
                });
            }
        }

        // Page 6: Transport Dashboard
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(40, 53, 147);
        doc.text("4. Transport Dashboard Analytics", 20, 20);

        if (transportStats && transportData.length > 0) {
            // Transport Metrics Dashboard
            doc.autoTable({
                startY: 30,
                head: [['Transport Metric', 'Average Value', 'Condition']],
                body: [
                    ['Traffic Congestion', transportStats.avgCongestion.toFixed(1) + '%', getCongestionStatus(transportStats.avgCongestion)],
                    ['Average Speed', transportStats.avgSpeed.toFixed(1) + ' km/h', transportStats.efficiency],
                    ['Traffic Index', transportStats.avgTrafficIndex.toFixed(1), ''],
                    ['Public Transport Usage', transportStats.totalPublicTransport ? (transportStats.totalPublicTransport / 1000000).toFixed(2) + 'M users' : 'N/A', ''],
                    ['Accident Rate', transportStats.totalAccidents + ' total', '']
                ],
                theme: 'striped',
                headStyles: { fillColor: [249, 115, 22] }
            });

            // Traffic Analysis
            const analysisY = doc.lastAutoTable.finalY + 15;
            doc.setFontSize(14);
            doc.setTextColor(40, 53, 147);
            doc.text("Traffic Pattern Analysis", 20, analysisY);

            doc.setFontSize(10);
            doc.setTextColor(0, 0, 0);
            const analysisText = `
Peak Hours: ${transportStats.peakHours || '8-10 AM, 5-7 PM'}
Weekly Pattern: ${transportStats.weeklyPattern || 'Heavier traffic on weekdays'}
Congestion Trend: ${transportStats.congestionTrend || 'Stable'}
Efficiency Rating: ${transportStats.efficiency || 'Moderate'}

RECOMMENDATIONS:
${transportStats.recommendations || '• Use public transport during peak hours\n• Consider alternative routes\n• Monitor real-time traffic updates'}
      `.trim();

            doc.text(analysisText, 20, analysisY + 10, { maxWidth: 170 });
        }

        // Page 7: Database Summary & User Activity
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(40, 53, 147);
        doc.text("Database Summary & User Activity", 20, 20);

        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);

        // Database Summary
        doc.autoTable({
            startY: 30,
            head: [['Data Module', 'Total Records', 'Latest Update']],
            body: [
                ['Population', populationData.length, populationData[0]?.year || 'N/A'],
                ['Infrastructure', infrastructureData.length, infrastructureData[0]?.year || 'N/A'],
                ['Environment', environmentData.length, environmentData[0] ? new Date(environmentData[0].createdAt).toLocaleDateString() : 'N/A'],
                ['Transport', transportData.length, transportData[0] ? new Date(transportData[0].date).toLocaleDateString() : 'N/A']
            ],
            theme: 'striped',
            headStyles: { fillColor: [40, 53, 147] }
        });

        // User Activity Summary
        const activityY = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.setTextColor(40, 53, 147);
        doc.text("User Activity Summary", 20, activityY);

        if (userActions.length > 0) {
            const loginCount = userActions.filter(action => action.action === 'LOGIN').length;
            const registerCount = userActions.filter(action => action.action === 'REGISTER').length;
            const predictCount = userActions.filter(action => action.action === 'PREDICT').length;
            const reportCount = userActions.filter(action => action.action === 'REPORT_GENERATED' || action.action === 'DASHBOARD_REPORT_GENERATED' || action.action === 'MODULE_DASHBOARD_REPORT').length;

            doc.autoTable({
                startY: activityY + 10,
                head: [['Activity Type', 'Count', 'Percentage']],
                body: [
                    ['Login', loginCount, ((loginCount / userActions.length) * 100).toFixed(1) + '%'],
                    ['Registration', registerCount, ((registerCount / userActions.length) * 100).toFixed(1) + '%'],
                    ['Predictions', predictCount, ((predictCount / userActions.length) * 100).toFixed(1) + '%'],
                    ['Reports Generated', reportCount, ((reportCount / userActions.length) * 100).toFixed(1) + '%'],
                    ['Total Actions', userActions.length, '100%']
                ],
                theme: 'grid',
                headStyles: { fillColor: [40, 53, 147] }
            });
        }

        // Footer on all pages
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
            doc.text(`Dashboard Report ID: ${city.toUpperCase()}-${Date.now().toString().slice(-8)}`, 105, 290, { align: 'center' });
        }

        // Convert to buffer and send
        const pdfBuffer = doc.output('arraybuffer');

        // Validate buffer
        validatePDFBuffer(Buffer.from(pdfBuffer));

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=${city}_dashboard_report_${Date.now()}.pdf`);
        res.setHeader('Content-Length', pdfBuffer.byteLength);

        // Send the PDF
        res.send(Buffer.from(pdfBuffer));

        // Log report generation
        const reportLog = new Data({
            userId,
            username,
            action: "DASHBOARD_REPORT_GENERATED",
            analysisResult: `Comprehensive dashboard report generated for ${city}`,
            city,
        });
        await reportLog.save();

    } catch (error) {
        console.error("❌ Dashboard Report Generation Error:", error);
        res.status(500).json({
            success: false,
            message: "Error generating dashboard report",
            error: error.message
        });
    }
};

// ✅ Generate module-specific dashboard report
export const generateModuleDashboardReport = async (req, res) => {
    try {
        const { module } = req.params;
        const userId = req.user.id;
        const city = req.query.city || "Pune";

        const doc = new jsPDF();

        // Header with dashboard style
        doc.setFontSize(20);
        doc.setTextColor(40, 53, 147);
        doc.text(`${module.charAt(0).toUpperCase() + module.slice(1)} Dashboard Report`, 105, 20, { align: 'center' });

        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`${city} Urban Analytics | ${new Date().toLocaleDateString()}`, 105, 30, { align: 'center' });

        // Add module-specific dashboard content
        switch (module) {
            case 'population':
                await addPopulationDashboard(doc, city);
                break;
            case 'infrastructure':
                await addInfrastructureDashboard(doc, city);
                break;
            case 'environment':
                await addEnvironmentDashboard(doc, userId, city);
                break;
            case 'transport':
                await addTransportDashboard(doc, city);
                break;
        }

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`${module.toUpperCase()} Dashboard Report - Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
        }

        const pdfBuffer = doc.output('arraybuffer');

        // Validate buffer
        validatePDFBuffer(Buffer.from(pdfBuffer));

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=${module}_dashboard_report_${city}_${Date.now()}.pdf`);
        res.setHeader('Content-Length', pdfBuffer.byteLength);

        res.send(Buffer.from(pdfBuffer));

        // Log module report generation
        const reportLog = new Data({
            userId,
            username: req.user.username,
            action: "MODULE_DASHBOARD_REPORT",
            analysisResult: `${module} dashboard report generated`,
            city,
        });
        await reportLog.save();

    } catch (error) {
        console.error(`❌ ${module} Dashboard Report Error:`, error);
        res.status(500).json({
            success: false,
            message: `Error generating ${module} dashboard report`,
            error: error.message
        });
    }
};

// ✅ Get report summary
export const getReportSummary = async (req, res) => {
    try {
        const userId = req.user.id;
        const city = req.query.city || "Pune";

        const summary = {
            population: await Population.countDocuments({ city }),
            infrastructure: await Infrastructure.countDocuments({ city }),
            environment: await Environment.countDocuments({ userId, city }),
            transport: await Transport.countDocuments({ city }),
            userActions: await Data.countDocuments({ userId }),
            lastGenerated: await Data.findOne({ userId, action: "DASHBOARD_REPORT_GENERATED" }).sort({ createdAt: -1 })
        };

        res.json({
            success: true,
            message: "Report summary fetched successfully",
            summary
        });
    } catch (error) {
        console.error("❌ Report Summary Error:", error);
        res.status(500).json({
            success: false,
            message: "Error fetching report summary",
            error: error.message
        });
    }
};

// Helper functions for dashboard calculations
function calculatePopulationStats(populationData) {
    if (!populationData || populationData.length === 0) return null;

    const latest = populationData[0];
    const earliest = populationData[populationData.length - 1];

    const totalGrowth = latest.totalPopulation - earliest.totalPopulation;
    const growthPercentage = (totalGrowth / earliest.totalPopulation * 100).toFixed(2);
    const avgGrowthRate = populationData.reduce((sum, item) => sum + item.growthRate, 0) / populationData.length;
    const avgDensity = populationData.reduce((sum, item) => sum + item.density, 0) / populationData.length;

    return {
        latestPopulation: latest.totalPopulation,
        avgGrowthRate: avgGrowthRate,
        avgDensity: avgDensity,
        growthTrend: avgGrowthRate > 2.5 ? 'Rapid Growth ↗' : avgGrowthRate > 1.5 ? 'Moderate Growth →' : 'Stable ↘',
        yearRange: {
            start: earliest.year,
            end: latest.year
        },
        totalGrowth: totalGrowth,
        growthPercentage: growthPercentage
    };
}

function calculateInfrastructureStats(infrastructureData) {
    if (!infrastructureData || infrastructureData.length === 0) return null;

    const latest = infrastructureData[0];
    const avgSmartScore = infrastructureData.reduce((sum, item) => sum + item.smartCityScore, 0) / infrastructureData.length;

    // Calculate scores like dashboard
    const roadsScore = Math.min(100, (latest.roadsKm / 1000) * 100);
    const healthScore = Math.min(100, (latest.hospitals / 100) * 100);
    const educationScore = Math.min(100, (latest.schools / 500) * 100);
    const housingScore = latest.housingIndex || 65;

    const overallScore = (
        roadsScore * 0.2 +
        healthScore * 0.2 +
        educationScore * 0.2 +
        housingScore * 0.2 +
        latest.smartCityScore * 0.2
    );

    return {
        roadsScore: roadsScore,
        healthScore: healthScore,
        educationScore: educationScore,
        housingScore: housingScore,
        smartCityScore: latest.smartCityScore,
        avgSmartScore: avgSmartScore,
        overallScore: overallScore,
        trend: latest.smartCityScore > 75 ? 'Improving ↗' : latest.smartCityScore > 60 ? 'Stable →' : 'Needs Attention ↘'
    };
}

function calculateEnvironmentStats(environmentData) {
    if (!environmentData || environmentData.length === 0) return null;

    const latest = environmentData[0];
    const avgAQI = environmentData.reduce((sum, item) => sum + (item.aqi || 0), 0) / environmentData.length;
    const avgPM25 = environmentData.reduce((sum, item) => sum + (item.pm25 || 0), 0) / environmentData.length;
    const avgGreenCover = environmentData.reduce((sum, item) => sum + (item.greenCover || 0), 0) / environmentData.length;

    return {
        avgAQI: avgAQI,
        avgPM25: avgPM25,
        avgGreenCover: avgGreenCover,
        pollutionLevel: latest.pollutionLevel || 'Moderate',
        lastUpdated: latest.createdAt,
        dataPoints: environmentData.length
    };
}

function calculateTransportStats(transportData) {
    if (!transportData || transportData.length === 0) return null;

    const avgCongestion = transportData.reduce((sum, item) => sum + (item.congestionLevel || 0), 0) / transportData.length;
    const avgSpeed = transportData.reduce((sum, item) => sum + (item.avgSpeed || 0), 0) / transportData.length;
    const avgTrafficIndex = transportData.reduce((sum, item) => sum + (item.trafficIndex || 0), 0) / transportData.length;
    const totalAccidents = transportData.reduce((sum, item) => sum + (item.accidents || 0), 0);
    const totalPublicTransport = transportData.reduce((sum, item) => sum + (item.publicTransportUsage || 0), 0);

    // Analyze patterns
    const weekdaysData = transportData.filter(item => {
        const date = new Date(item.date);
        return date.getDay() >= 1 && date.getDay() <= 5;
    });

    const weekendData = transportData.filter(item => {
        const date = new Date(item.date);
        return date.getDay() === 0 || date.getDay() === 6;
    });

    const weekdayCongestion = weekdaysData.reduce((sum, item) => sum + (item.congestionLevel || 0), 0) / (weekdaysData.length || 1);
    const weekendCongestion = weekendData.reduce((sum, item) => sum + (item.congestionLevel || 0), 0) / (weekendData.length || 1);

    return {
        avgCongestion: avgCongestion,
        avgSpeed: avgSpeed,
        avgTrafficIndex: avgTrafficIndex,
        totalAccidents: totalAccidents,
        totalPublicTransport: totalPublicTransport,
        peakHours: '8-10 AM, 5-7 PM',
        weeklyPattern: weekdayCongestion > weekendCongestion + 10 ? 'Heavier on weekdays' : 'Even distribution',
        congestionTrend: avgCongestion > 70 ? 'High ↗' : avgCongestion > 50 ? 'Moderate →' : 'Low ↘',
        efficiency: avgSpeed > 40 ? 'Good Flow ✅' : avgSpeed > 25 ? 'Moderate ⚠️' : 'Poor 🚫',
        recommendations: avgCongestion > 70 ? 'Use public transport\nAvoid peak hours\nConsider alternative routes' : 'Normal traffic conditions'
    };
}

// Helper functions for module dashboards
async function addPopulationDashboard(doc, city) {
    const populationData = await Population.find({ city }).sort({ year: -1 });
    const stats = calculatePopulationStats(populationData);

    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Population Dashboard Overview", 20, 45);

    if (stats) {
        doc.autoTable({
            startY: 55,
            head: [['Dashboard Metric', 'Value', 'Status']],
            body: [
                ['Total Population', (stats.latestPopulation / 1000000).toFixed(3) + ' Million', 'Current'],
                ['Annual Growth Rate', stats.avgGrowthRate.toFixed(2) + '%', getTrendIcon(stats.avgGrowthRate)],
                ['Population Density', stats.avgDensity.toLocaleString() + ' per km²', 'Urban Density'],
                ['Growth Period', `${stats.yearRange.start}-${stats.yearRange.end}`, `${stats.growthPercentage}% total growth`],
                ['Urbanization Trend', stats.growthTrend, '']
            ],
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] }
        });
    }

    // Add database data
    if (populationData.length > 0) {
        const dbY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 120;
        doc.setFontSize(14);
        doc.setTextColor(40, 53, 147);
        doc.text("Database Records", 20, dbY);

        const tableData = populationData.slice(0, 10).map(pop => [
            pop.year,
            (pop.totalPopulation / 1000000).toFixed(3) + 'M',
            pop.growthRate + '%',
            pop.density.toLocaleString()
        ]);

        doc.autoTable({
            startY: dbY + 10,
            head: [['Year', 'Population', 'Growth', 'Density']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] }
        });
    }
}

async function addInfrastructureDashboard(doc, city) {
    const infrastructureData = await Infrastructure.find({ city }).sort({ year: -1 });
    const stats = calculateInfrastructureStats(infrastructureData);

    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Infrastructure Dashboard Overview", 20, 45);

    if (stats) {
        doc.autoTable({
            startY: 55,
            head: [['Infrastructure Component', 'Current Value', 'Score/Status']],
            body: [
                ['Smart City Index', infrastructureData[0]?.smartCityScore + '/100' || 'N/A', infrastructureData[0]?.smartCityScore > 75 ? 'Excellent' : 'Good'],
                ['Road Network', infrastructureData[0]?.roadsKm + ' km' || 'N/A', stats.roadsScore ? stats.roadsScore.toFixed(1) + '/100' : 'N/A'],
                ['Healthcare Facilities', infrastructureData[0]?.hospitals || 'N/A', stats.healthScore ? stats.healthScore.toFixed(1) + '/100' : 'N/A'],
                ['Education Institutions', infrastructureData[0]?.schools || 'N/A', stats.educationScore ? stats.educationScore.toFixed(1) + '/100' : 'N/A'],
                ['Overall Score', stats.overallScore ? stats.overallScore.toFixed(1) + '/100' : 'N/A', stats.trend || '']
            ],
            theme: 'striped',
            headStyles: { fillColor: [139, 92, 246] }
        });
    }

    // Add database data
    if (infrastructureData.length > 0) {
        const dbY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 120;
        doc.setFontSize(14);
        doc.setTextColor(40, 53, 147);
        doc.text("Infrastructure Development Records", 20, dbY);

        const tableData = infrastructureData.slice(0, 10).map(infra => [
            infra.year,
            infra.roadsKm + ' km',
            infra.hospitals,
            infra.schools,
            infra.smartCityScore + '/100'
        ]);

        doc.autoTable({
            startY: dbY + 10,
            head: [['Year', 'Roads', 'Hospitals', 'Schools', 'Smart Score']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [139, 92, 246] }
        });
    }
}

async function addEnvironmentDashboard(doc, userId, city) {
    const environmentData = await Environment.find({ userId, city }).sort({ createdAt: -1 });
    const stats = calculateEnvironmentStats(environmentData);

    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Environment Dashboard Overview", 20, 45);

    if (stats) {
        doc.autoTable({
            startY: 55,
            head: [['Parameter', 'Average Value', 'Status']],
            body: [
                ['Air Quality Index', stats.avgAQI.toFixed(1), getAQIStatus(stats.avgAQI)],
                ['PM2.5 Levels', stats.avgPM25.toFixed(1) + ' µg/m³', getPM25Status(stats.avgPM25)],
                ['Green Cover', stats.avgGreenCover.toFixed(1) + '%', getGreenCoverStatus(stats.avgGreenCover)],
                ['Pollution Level', stats.pollutionLevel, ''],
                ['Data Reliability', environmentData.length + ' readings', 'Based on recent measurements']
            ],
            theme: 'striped',
            headStyles: { fillColor: [34, 197, 94] }
        });
    }

    // Add database data
    if (environmentData.length > 0) {
        const dbY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 120;
        doc.setFontSize(14);
        doc.setTextColor(40, 53, 147);
        doc.text("Environmental Readings Database", 20, dbY);

        const tableData = environmentData.slice(0, 10).map(env => [
            new Date(env.createdAt).toLocaleDateString(),
            env.aqi || 'N/A',
            env.pm25 || 'N/A',
            env.greenCover || 'N/A',
            env.pollutionLevel || 'N/A'
        ]);

        doc.autoTable({
            startY: dbY + 10,
            head: [['Date', 'AQI', 'PM2.5', 'Green Cover', 'Pollution']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [34, 197, 94] }
        });
    }
}

async function addTransportDashboard(doc, city) {
    const transportData = await Transport.find({ city }).sort({ date: -1 });
    const stats = calculateTransportStats(transportData);

    doc.setFontSize(16);
    doc.setTextColor(40, 53, 147);
    doc.text("Transport Dashboard Overview", 20, 45);

    if (stats) {
        doc.autoTable({
            startY: 55,
            head: [['Transport Metric', 'Average Value', 'Condition']],
            body: [
                ['Traffic Congestion', stats.avgCongestion.toFixed(1) + '%', getCongestionStatus(stats.avgCongestion)],
                ['Average Speed', stats.avgSpeed.toFixed(1) + ' km/h', stats.efficiency],
                ['Traffic Index', stats.avgTrafficIndex.toFixed(1), ''],
                ['Public Transport', stats.totalPublicTransport ? (stats.totalPublicTransport / 1000000).toFixed(2) + 'M users' : 'N/A', ''],
                ['Weekly Pattern', stats.weeklyPattern, stats.peakHours + ' peak']
            ],
            theme: 'striped',
            headStyles: { fillColor: [249, 115, 22] }
        });
    }

    // Add database data
    if (transportData.length > 0) {
        const dbY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 120;
        doc.setFontSize(14);
        doc.setTextColor(40, 53, 147);
        doc.text("Transport Database Records", 20, dbY);

        const tableData = transportData.slice(0, 10).map(trans => [
            new Date(trans.date).toLocaleDateString(),
            trans.congestionLevel || 'N/A',
            trans.avgSpeed || 'N/A',
            trans.trafficIndex || 'N/A'
        ]);

        doc.autoTable({
            startY: dbY + 10,
            head: [['Date', 'Congestion%', 'Avg Speed', 'Traffic Index']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [249, 115, 22] }
        });
    }
}

// Utility functions
function getTrendIcon(growthRate) {
    if (growthRate > 2.5) return '↗ Rapid Growth';
    if (growthRate > 1.5) return '→ Moderate Growth';
    return '↘ Stable';
}

function getAQIStatus(aqi) {
    if (!aqi) return 'N/A';
    if (aqi <= 50) return 'Good ✅';
    if (aqi <= 100) return 'Moderate ⚠️';
    if (aqi <= 150) return 'Unhealthy for Sensitive Groups ❗';
    if (aqi <= 200) return 'Unhealthy 🚫';
    return 'Hazardous ☠️';
}

function getPM25Status(pm25) {
    if (!pm25) return 'N/A';
    if (pm25 <= 12) return 'Good';
    if (pm25 <= 35) return 'Moderate';
    if (pm25 <= 55) return 'Unhealthy';
    return 'Hazardous';
}

function getGreenCoverStatus(cover) {
    if (!cover) return 'N/A';
    if (cover > 30) return 'Excellent';
    if (cover > 20) return 'Good';
    if (cover > 10) return 'Moderate';
    return 'Poor';
}

function getCongestionStatus(congestion) {
    if (!congestion) return 'N/A';
    if (congestion <= 30) return 'Light Traffic ✅';
    if (congestion <= 50) return 'Moderate Traffic ⚠️';
    if (congestion <= 70) return 'Heavy Traffic ❗';
    return 'Severe Congestion 🚫';
}

function getPollutionText(level) {
    switch (level) {
        case 'Good': return 'Good air quality with minimal pollution';
        case 'Moderate': return 'Moderate pollution levels, acceptable for most';
        case 'Unhealthy': return 'Elevated pollution, sensitive groups should take precautions';
        case 'Hazardous': return 'Severe pollution, all individuals should avoid exposure';
        default: return 'Moderate environmental conditions';
    }
}

function generateDashboardRecommendations(popStats, infraStats, envStats, transStats) {
    const recommendations = [];

    if (popStats && popStats.avgGrowthRate > 2.5) {
        recommendations.push('• Accelerate infrastructure development to accommodate rapid population growth');
    }

    if (infraStats && infraStats.overallScore < 70) {
        recommendations.push('• Increase investment in smart city infrastructure and public services');
    }

    if (envStats && envStats.avgAQI > 100) {
        recommendations.push('• Implement stricter pollution control measures and increase green spaces');
    }

    if (transStats && transStats.avgCongestion > 60) {
        recommendations.push('• Enhance public transportation system and implement smart traffic management');
    }

    if (envStats && envStats.avgGreenCover < 20) {
        recommendations.push('• Launch urban greening initiatives and park development programs');
    }

    if (recommendations.length === 0) {
        recommendations.push('• Continue current urban development strategies');
        recommendations.push('• Monitor key metrics for early intervention and optimization');
        recommendations.push('• Maintain sustainable growth practices');
    }

    return '\nURBAN PLANNING RECOMMENDATIONS:\n' + recommendations.join('\n');
}